export const Colors = {
  primaryColor: '#988DFF',
  Green: '#45E1C6',
  White: '#FFFFFF',
  lightGreen: '#D4FFF6',
  Red: '#FF709B',
  lightRed: '#FFEAF2',
  emotionColor: '#A2AAFF',
  mimicColor: '#AD99FF',
  facialColor: '#FDA0FF',
  manipulationColor: '#D49DFF',
  bodyColor: '#878DFF',
  coldReadingColor: '#FF93E7',
  dark: '#3E3872',
  borderColor: '#E4E0EF',
  buttonColor: '#F3F3FF',
  accent: '#B4FFEF',
  redAccent: '#ffb2c9',
  modelText: '#78749C',
  primaryTransparent: '#988DFF33',
  reviewFilledColor: '#FFE03E',
  disabled: '#D8F6EF',
};
